### ISSUE TITLE
Signed integer is greater than maximum in get_cal_images.py

### ISSUE THREAD

**Issue by xwxing1229** [wilselby/openmv_cam#2]
Hi. I am following your blog to use OpenMV in ROS. When I try to do the calibration, it shows that:
Traceback (most recent call last):
  File "get_cal_images.py", line 22, in <module>
    buf = serial_port.read(size)
  File "/usr/lib/python2.7/dist-packages/serial/serialposix.py", line 488, in read
    buf = os.read(self.fd, size - len(read))
OverflowError: signed integer is greater than maximum

I am using Python 2.7. Do you know how to solve this problem? Thanks for your guide.

**Comment by xwxing1229** [comment]
> Hi. I am following your blog to use OpenMV in ROS. When I try to do the calibration, it shows that:
> Traceback (most recent call last):
> File "get_cal_images.py", line 22, in 
> buf = serial_port.read(size)
> File "/usr/lib/python2.7/dist-packages/serial/serialposix.py", line 488, in read
> buf = os.read(self.fd, size - len(read))
> OverflowError: signed integer is greater than maximum
> 
> I am using Python 2.7. Do you know how to solve this problem? Thanks for your guide.

It has been solved. I change nothing and then it works...
